# IRIS Dataset

### Import libraries

In [84]:
import pandas as pd
import matplotlib as plt
import numpy as np

%matplotlib inline

## Load and review data

In [138]:
df = pd.read_csv("iris_csv.csv")

In [139]:
df.shape

(150, 5)

In [140]:
df.head(5)

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

## Check for null values

In [141]:
df.isnull().values.any()

False

In [142]:
df.corr()

             sepallength  sepalwidth  petallength  petalwidth
sepallength     1.000000   -0.109369     0.871754    0.817954
sepalwidth     -0.109369    1.000000    -0.420516   -0.356544
petallength     0.871754   -0.420516     1.000000    0.962757
petalwidth      0.817954   -0.356544     0.962757    1.000000

## Check Data Types

In [143]:
df.head(5)

   sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

I have to change the class from categorical to numeric value.
I will use LabelEncoder from pandas.

In [144]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cicek = df.iloc[:,-1].values
print(cicek)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']

### Change them to numeric value.

In [145]:
cicek = le.fit_transform(cicek)
print(cicek)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

### Add them into that origin dataset.

In [146]:
cicek = pd.DataFrame(data = cicek, index = range(150), columns = ['class'])
df= df.iloc[:,:4]
df = pd.concat([df,cicek], axis=1)
df.head(100)

    sepallength  sepalwidth  petallength  petalwidth  class
0           5.1         3.5          1.4         0.2      0
1           4.9         3.0          1.4         0.2      0
2           4.7         3.2          1.3         0.2      0
3           4.6         3.1          1.5         0.2      0
4           5.0         3.6          1.4         0.2      0
5           5.4         3.9          1.7         0.4      0
6           4.6         3.4          1.4         0.3      0
7           5.0         3.4          1.5         0.2      0
8           4.4         2.9          1.4         0.2      0
9           4.9         3.1          1.5         0.1      0
10          5.4         3.7          1.5         0.2      0
11          4.8         3.4          1.6         0.2      0
12          4.8         3.0          1.4         0.1      0
13          4.3         3.0          1.1         0.1      0
14          5.8         4.0          1.2         0.2      0
15          5.7         4.4          1.5         0.4      0
16          5.4         3.9          1.3         0.4      0
17          5.1         3.5          1.4         0.3      0
18          5.7         3.8          1.7         0.3      0
19          5.1         3.8          1.5         0.3      0
20          5.4         3.4          1.7         0.2      0
21          5.1         3.7          1.5         0.4      0
22          4.6         3.6          1.0         0.2      0
23          5.1         3.3          1.7         0.5      0
24          4.8         3.4          1.9         0.2      0
25          5.0         3.0          1.6         0.2      0
26          5.0         3.4          1.6         0.4      0
27          5.2         3.5          1.5         0.2      0
28          5.2         3.4          1.4         0.2      0
29          4.7         3.2          1.6         0.2      0
..          ...         ...          ...         ...    ...
70          5.9         3.2          4.8         1.8      1
71          6.1         2.8          4.0         1.3      1
72          6.3         2.5          4.9         1.5      1
73          6.1         2.8          4.7         1.2      1
74          6.4         2.9          4.3         1.3      1
75          6.6         3.0          4.4         1.4      1
76          6.8         2.8          4.8         1.4      1
77          6.7         3.0          5.0         1.7      1
78          6.0         2.9          4.5         1.5      1
79          5.7         2.6          3.5         1.0      1
80          5.5         2.4          3.8         1.1      1
81          5.5         2.4          3.7         1.0      1
82          5.8         2.7          3.9         1.2      1
83          6.0         2.7          5.1         1.6      1
84          5.4         3.0          4.5         1.5      1
85          6.0         3.4          4.5         1.6      1
86          6.7         3.1          4.7         1.5      1
87          6.3         2.3          4.4         1.3      1
88          5.6         3.0          4.1         1.3      1
89          5.5         2.5          4.0         1.3      1
90          5.5         2.6          4.4         1.2      1
91          6.1         3.0          4.6         1.4      1
92          5.8         2.6          4.0         1.2      1
93          5.0         2.3          3.3         1.0      1
94          5.6         2.7          4.2         1.3      1
95          5.7         3.0          4.2         1.2      1
96          5.7         2.9          4.2         1.3      1
97          6.2         2.9          4.3         1.3      1
98          5.1         2.5          3.0         1.1      1
99          5.7         2.8          4.1         1.3      1

[100 rows x 5 columns]

## Check 0-1-2 ratio

In [148]:
cicek_zero = len(df.loc[df['class'] == '0'])
cicek_one = len(df.loc[df['class'] == '1'])
cicek_two = len(df.loc[df['class'] == '2'])

print("Number of True Cases: {0} ({1:2.2f}%)".format(cicek_zero, (cicek_zero/ (cicek_zero + cicek_one + cicek_two )) * 100))

d:\Users\Asli\Anaconda3\lib\site-packages\pandas\core\ops.py:1167: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

TypeError: invalid type comparison

## Splitting the data

%70 for training, %30 for testing.

In [ ]:
#from sklearn.cross_validation import train_test_split

#feature_col_names = ['sepallength', 'sepalwidth', '']